name: Go

on:
  push:
    branches: [ main ]
  schedule: 
    - cron: 0 0/2 * * *

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
        go build .
        ./bding -secret ${{ secrets.DING_SECRETS }} -token ${{ secrets.DING_ACCESS_TOKEN }}
